package com.example.dto

import javax.annotation.processing.Generated

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
public inline fun Address.mutate(block: Address.BuilderMutator.() -> Unit): Address =
    this.mutate().also { it.block() }.build()

