package com.example.dto

import javax.annotation.processing.Generated

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
public inline fun Manifest.mutate(block: Manifest.BuilderMutator.() -> Unit): Manifest =
    this.mutate().also { it.block() }.build()

