package com.example.dto

import javax.annotation.processing.Generated

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
public inline fun Money.mutate(block: Money.BuilderMutator.() -> Unit): Money =
    this.mutate().also { it.block() }.build()

