package com.example.dto

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

public inline fun Money.mutate(block: Money.BuilderMutator.() -> Unit): Money =
    this.mutate().also { it.block() }.build()

