package com.example.dto

import javax.annotation.processing.Generated

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
public inline fun Order.mutate(block: Order.BuilderMutator.() -> Unit): Order =
    this.mutate().also { it.block() }.build()

