package com.example.dto

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

public inline fun Shipment.mutate(block: Shipment.BuilderMutator.() -> Unit): Shipment =
    this.mutate().also { it.block() }.build()

