package com.example.dto

import javax.annotation.processing.Generated

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
public inline fun Tag.mutate(block: Tag.BuilderMutator.() -> Unit): Tag =
    this.mutate().also { it.block() }.build()

