package com.example.dto

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

public inline fun Address.mutate(block: Address.BuilderMutator.() -> Unit): Address =
    this.mutate().also { it.block() }.build()

