package com.example.dto

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

public inline fun Blob.mutate(block: Blob.BuilderMutator.() -> Unit): Blob =
    this.mutate().also { it.block() }.build()

