package com.example.dto

import javax.annotation.processing.Generated

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
public inline fun Invoice.mutate(block: Invoice.BuilderMutator.() -> Unit): Invoice =
    this.mutate().also { it.block() }.build()

@Generated("io.github.malczuuu.modelmaker")
public inline fun Invoice.Contact.mutate(block: Invoice.Contact.BuilderMutator.() -> Unit): Invoice.Contact =
    this.mutate().also { it.block() }.build()

@Generated("io.github.malczuuu.modelmaker")
public inline fun Invoice.Note.mutate(block: Invoice.Note.BuilderMutator.() -> Unit): Invoice.Note =
    this.mutate().also { it.block() }.build()

