package com.example.dto

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

public inline fun Invoice.mutate(block: Invoice.BuilderMutator.() -> Unit): Invoice =
    this.mutate().also { it.block() }.build()

public inline fun Invoice.Contact.mutate(block: Invoice.Contact.BuilderMutator.() -> Unit): Invoice.Contact =
    this.mutate().also { it.block() }.build()

public inline fun Invoice.Note.mutate(block: Invoice.Note.BuilderMutator.() -> Unit): Invoice.Note =
    this.mutate().also { it.block() }.build()

