package com.example.dto

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

public inline fun LineItem.mutate(block: LineItem.BuilderMutator.() -> Unit): LineItem =
    this.mutate().also { it.block() }.build()

