package com.example.dto

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

public inline fun Manifest.mutate(block: Manifest.BuilderMutator.() -> Unit): Manifest =
    this.mutate().also { it.block() }.build()

