package com.example.dto

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

public inline fun Order.mutate(block: Order.BuilderMutator.() -> Unit): Order =
    this.mutate().also { it.block() }.build()

