package com.example.dto

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

public inline fun Tag.mutate(block: Tag.BuilderMutator.() -> Unit): Tag =
    this.mutate().also { it.block() }.build()

