package com.example.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
@NullMarked
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonPropertyOrder({"id", "status", "distance", "weight", "priority"})
public final class Shipment {

  private final String id;

  private final String status;

  private final Long distance;

  private final Float weight;

  private final String priority;

  @JsonCreator
  Shipment(
      @JsonProperty("id") String id,
      @JsonProperty("status") String status,
      @JsonProperty("distance") Long distance,
      @JsonProperty("weight") Float weight,
      @JsonProperty("priority") @Nullable String priority) {
    this.id = id;
    this.status = status;
    this.distance = distance;
    this.weight = weight;
    this.priority = priority != null ? priority : "NORMAL";
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("status")
  public String getStatus() {
    return status;
  }

  @JsonProperty("distance")
  public Long getDistance() {
    return distance;
  }

  @JsonProperty("weight")
  public Float getWeight() {
    return weight;
  }

  @JsonProperty("priority")
  public String getPriority() {
    return priority;
  }

  public Builder mutate() {
    return builder()
        .id(id)
        .status(status)
        .distance(distance)
        .weight(weight)
        .priority(priority);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Shipment other)) {
      return false;
    }
    return Objects.equals(id, other.id)
      && Objects.equals(status, other.status)
      && Objects.equals(distance, other.distance)
      && Objects.equals(weight, other.weight)
      && Objects.equals(priority, other.priority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, distance, weight, priority);
  }

  @Override
  public String toString() {
    return "Shipment["
      + "id=" + id
      + ", status=" + status
      + ", distance=" + distance
      + ", weight=" + weight
      + ", priority=" + priority
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  @Generated("io.github.malczuuu.modelmaker")
  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String id;
    private @Nullable String status;
    private @Nullable Long distance;
    private @Nullable Float weight;
    private @Nullable String priority;

    @Override
    public Builder id(@Nullable String id) {
      this.id = id;
      return this;
    }

    @Override
    public Builder status(@Nullable String status) {
      this.status = status;
      return this;
    }

    @Override
    public Builder distance(@Nullable Long distance) {
      this.distance = distance;
      return this;
    }

    @Override
    public Builder weight(@Nullable Float weight) {
      this.weight = weight;
      return this;
    }

    @Override
    public Builder priority(@Nullable String priority) {
      this.priority = priority;
      return this;
    }

    @Override
    public String toString() {
      return "Shipment.Builder["
        + "id=" + id
        + ", status=" + status
        + ", distance=" + distance
        + ", weight=" + weight
        + ", priority=" + priority
        + "]";
    }

    public Shipment build() {
      return new Shipment(
          Objects.requireNonNull(id, "id is required"),
          Objects.requireNonNull(status, "status is required"),
          Objects.requireNonNull(distance, "distance is required"),
          Objects.requireNonNull(weight, "weight is required"),
          priority);
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  public sealed interface BuilderMutator permits Builder {

    BuilderMutator id(@Nullable String id);

    BuilderMutator status(@Nullable String status);

    BuilderMutator distance(@Nullable Long distance);

    BuilderMutator weight(@Nullable Float weight);

    BuilderMutator priority(@Nullable String priority);
  }
}
