package com.example.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@NullMarked
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonPropertyOrder({"currency", "amount", "scale", "taxable"})
public final class Money {

  private final String currency;

  private final Double amount;

  private final Integer scale;

  private final Boolean taxable;

  @JsonCreator
  Money(
      @JsonProperty("currency") String currency,
      @JsonProperty("amount") Double amount,
      @JsonProperty("scale") Integer scale,
      @JsonProperty("taxable") Boolean taxable) {
    this.currency = currency;
    this.amount = amount;
    this.scale = scale;
    this.taxable = taxable;
  }

  @JsonProperty("currency")
  public String getCurrency() {
    return currency;
  }

  @JsonProperty("amount")
  public Double getAmount() {
    return amount;
  }

  @JsonProperty("scale")
  public Integer getScale() {
    return scale;
  }

  @JsonProperty("taxable")
  public Boolean getTaxable() {
    return taxable;
  }

  public Builder mutate() {
    return builder()
        .currency(currency)
        .amount(amount)
        .scale(scale)
        .taxable(taxable);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Money other)) {
      return false;
    }
    return Objects.equals(currency, other.currency)
      && Objects.equals(amount, other.amount)
      && Objects.equals(scale, other.scale)
      && Objects.equals(taxable, other.taxable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, amount, scale, taxable);
  }

  @Override
  public String toString() {
    return "Money["
      + "currency=" + currency
      + ", amount=" + amount
      + ", scale=" + scale
      + ", taxable=" + taxable
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String currency;
    private @Nullable Double amount;
    private @Nullable Integer scale;
    private @Nullable Boolean taxable;

    @Override
    public Builder currency(@Nullable String currency) {
      this.currency = currency;
      return this;
    }

    @Override
    public Builder amount(@Nullable Double amount) {
      this.amount = amount;
      return this;
    }

    @Override
    public Builder scale(@Nullable Integer scale) {
      this.scale = scale;
      return this;
    }

    @Override
    public Builder taxable(@Nullable Boolean taxable) {
      this.taxable = taxable;
      return this;
    }

    @Override
    public String toString() {
      return "Money.Builder["
        + "currency=" + currency
        + ", amount=" + amount
        + ", scale=" + scale
        + ", taxable=" + taxable
        + "]";
    }

    public Money build() {
      return new Money(
          Objects.requireNonNull(currency, "currency is required"),
          Objects.requireNonNull(amount, "amount is required"),
          Objects.requireNonNull(scale, "scale is required"),
          Objects.requireNonNull(taxable, "taxable is required"));
    }
  }

  public sealed interface BuilderMutator permits Builder {

    BuilderMutator currency(@Nullable String currency);

    BuilderMutator amount(@Nullable Double amount);

    BuilderMutator scale(@Nullable Integer scale);

    BuilderMutator taxable(@Nullable Boolean taxable);
  }
}
