package com.example.dto

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

public inline fun Kit.mutate(block: Kit.BuilderMutator.() -> Unit): Kit =
    this.mutate().also { it.block() }.build()

