package com.example.dto

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

public inline fun Widget.mutate(block: Widget.BuilderMutator.() -> Unit): Widget =
    this.mutate().also { it.block() }.build()

