package com.example.dto

import javax.annotation.processing.Generated

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
public inline fun Widget.mutate(block: Widget.BuilderMutator.() -> Unit): Widget =
    this.mutate().also { it.block() }.build()

