/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.modelmaker;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatNullPointerException;

import java.util.List;
import org.junit.jupiter.api.Test;

class KotlinExtensionMakerTest {

  private final ModelType order =
      new ModelType(
          "Order",
          "com.example.dto",
          null,
          List.of(
              new Property(
                  "ref", PropType.RefType.of("Address"), true, Constraints.none(), "ref", null),
              new Property(
                  "line", PropType.RefType.of("Line"), true, Constraints.none(), "line", null)),
          List.of(
              new ModelType(
                  "Line",
                  "",
                  "An inline nested object.",
                  List.of(
                      new Property(
                          "sku",
                          PropType.ScalarType.STRING,
                          true,
                          Constraints.none(),
                          "sku",
                          null)),
                  List.of(),
                  FeatureOverrides.none())),
          FeatureOverrides.none());

  @Test
  void emitsAMutateExtensionPerTypeTopLevelAndNested() {
    String out = new KotlinExtensionMaker().emit(order);

    assertThat(out).contains("package com.example.dto");
    assertThat(out).doesNotContain("@Generated");
    // Do-not-edit banner: one blank line after the package, one before the first declaration.
    assertThat(out)
        .contains(
            "package com.example.dto\n\n// Generated by ModelMaker"
                + " (io.github.malczuuu.modelmaker). Do not edit manually.\n\npublic inline fun"
                + " Order.mutate(block: Order.BuilderMutator.() -> Unit): Order =");
    assertThat(out).contains("this.mutate().also { it.block() }.build()");
    // Nested types get a mutate extension too.
    assertThat(out)
        .contains(
            "public inline fun Order.Line.mutate(block: Order.Line.BuilderMutator.() -> Unit):"
                + " Order.Line =");
    // No constructor-alike factory extension.
    assertThat(out).doesNotContain("Order.builder().apply(block)");
    assertThat(out).doesNotContain("public inline fun Order(block");
  }

  @Test
  void aPropertyLessTypeGetsNoExtension() {
    ModelType empty =
        new ModelType(
            "Empty", "com.example.dto", null, List.of(), List.of(), FeatureOverrides.none());
    assertThat(new KotlinExtensionMaker().emit(empty)).isEqualTo("package com.example.dto\n\n");
  }

  @Test
  void emitRejectsANullType() {
    assertThatNullPointerException().isThrownBy(() -> new KotlinExtensionMaker().emit(null));
  }
}
