package com.example.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.util.Objects;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
@NullMarked
@Schema(description = "A postal address.")
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonPropertyOrder({"city", "postalCode"})
public final class Address {

  private final String city;

  private final String postalCode;

  @JsonCreator
  Address(
      @JsonProperty("city") String city,
      @JsonProperty("postalCode") String postalCode) {
    this.city = city;
    this.postalCode = postalCode;
  }

  @Schema(description = "City name.", example = "Kraków", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("city")
  @NotNull(message = "must not be null")
  @Size(min = 1, message = "size must be at least 1")
  public String getCity() {
    return city;
  }

  @Schema(description = "Polish postal code, NN-NNN.", example = "30-001", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("postalCode")
  @NotNull(message = "must not be null")
  @Pattern(regexp = "^\\d{2}-\\d{3}$", message = "must match \"^\\d{2}-\\d{3}$\"")
  public String getPostalCode() {
    return postalCode;
  }

  public Builder mutate() {
    return builder()
        .city(city)
        .postalCode(postalCode);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Address other)) {
      return false;
    }
    return Objects.equals(city, other.city)
      && Objects.equals(postalCode, other.postalCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, postalCode);
  }

  @Override
  public String toString() {
    return "Address["
      + "city=" + city
      + ", postalCode=" + postalCode
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  @Generated("io.github.malczuuu.modelmaker")
  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String city;
    private @Nullable String postalCode;

    @Override
    public Builder city(@Nullable String city) {
      this.city = city;
      return this;
    }

    @Override
    public Builder postalCode(@Nullable String postalCode) {
      this.postalCode = postalCode;
      return this;
    }

    @Override
    public String toString() {
      return "Address.Builder["
        + "city=" + city
        + ", postalCode=" + postalCode
        + "]";
    }

    public Address build() {
      return new Address(
          Objects.requireNonNull(city, "city is required"),
          Objects.requireNonNull(postalCode, "postalCode is required"));
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  public sealed interface BuilderMutator permits Builder {

    BuilderMutator city(@Nullable String city);

    BuilderMutator postalCode(@Nullable String postalCode);
  }
}
