package com.example.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import java.util.Objects;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@NullMarked
@Schema(description = "Combines Jackson binding, jakarta.validation constraints and OpenAPI @Schema metadata on one type.")
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonPropertyOrder({"id", "email", "loyaltyPoints", "shippingAddress"})
public final class Customer {

  private final String id;

  private final String email;

  private final Integer loyaltyPoints;

  private final Address shippingAddress;

  @JsonCreator
  Customer(
      @JsonProperty("id") String id,
      @JsonProperty("email") String email,
      @JsonProperty("loyaltyPoints") @Nullable Integer loyaltyPoints,
      @JsonProperty("shippingAddress") Address shippingAddress) {
    this.id = id;
    this.email = email;
    this.loyaltyPoints = loyaltyPoints != null ? loyaltyPoints : 0;
    this.shippingAddress = shippingAddress;
  }

  @Schema(description = "Customer identifier, C followed by digits.", example = "C42", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("id")
  @NotNull(message = "must not be null")
  @Pattern(regexp = "^C\\d+$", message = "must match \"^C\\d+$\"")
  public String getId() {
    return id;
  }

  @Schema(description = "Primary contact email.", example = "ada@example.com", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("email")
  @NotNull(message = "must not be null")
  @Email(message = "must be a well-formed email address")
  public String getEmail() {
    return email;
  }

  @Schema(description = "Accrued loyalty points.")
  @JsonProperty("loyaltyPoints")
  @NotNull(message = "must not be null")
  @Min(value = 0, message = "must be greater than or equal to 0")
  @Max(value = 100000, message = "must be less than or equal to 100000")
  public Integer getLoyaltyPoints() {
    return loyaltyPoints;
  }

  @JsonProperty("shippingAddress")
  @NotNull(message = "must not be null")
  @Valid
  public Address getShippingAddress() {
    return shippingAddress;
  }

  public Builder mutate() {
    return builder()
        .id(id)
        .email(email)
        .loyaltyPoints(loyaltyPoints)
        .shippingAddress(shippingAddress);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Customer other)) {
      return false;
    }
    return Objects.equals(id, other.id)
      && Objects.equals(email, other.email)
      && Objects.equals(loyaltyPoints, other.loyaltyPoints)
      && Objects.equals(shippingAddress, other.shippingAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, email, loyaltyPoints, shippingAddress);
  }

  @Override
  public String toString() {
    return "Customer["
      + "id=" + id
      + ", email=" + email
      + ", loyaltyPoints=" + loyaltyPoints
      + ", shippingAddress=" + shippingAddress
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String id;
    private @Nullable String email;
    private @Nullable Integer loyaltyPoints;
    private @Nullable Address shippingAddress;

    @Override
    public Builder id(@Nullable String id) {
      this.id = id;
      return this;
    }

    @Override
    public Builder email(@Nullable String email) {
      this.email = email;
      return this;
    }

    @Override
    public Builder loyaltyPoints(@Nullable Integer loyaltyPoints) {
      this.loyaltyPoints = loyaltyPoints;
      return this;
    }

    @Override
    public Builder shippingAddress(@Nullable Address shippingAddress) {
      this.shippingAddress = shippingAddress;
      return this;
    }

    @Override
    public String toString() {
      return "Customer.Builder["
        + "id=" + id
        + ", email=" + email
        + ", loyaltyPoints=" + loyaltyPoints
        + ", shippingAddress=" + shippingAddress
        + "]";
    }

    public Customer build() {
      return new Customer(
          Objects.requireNonNull(id, "id is required"),
          Objects.requireNonNull(email, "email is required"),
          loyaltyPoints,
          Objects.requireNonNull(shippingAddress, "shippingAddress is required"));
    }
  }

  public sealed interface BuilderMutator permits Builder {

    BuilderMutator id(@Nullable String id);

    BuilderMutator email(@Nullable String email);

    BuilderMutator loyaltyPoints(@Nullable Integer loyaltyPoints);

    BuilderMutator shippingAddress(@Nullable Address shippingAddress);
  }
}
