package com.example.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import java.util.Objects;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@NullMarked
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonPropertyOrder({"street", "city", "kind"})
public final class Address {

  private final String street;

  private final String city;

  private final String kind;

  @JsonCreator
  Address(
      @JsonProperty("street") String street,
      @JsonProperty("city") String city,
      @JsonProperty("kind") String kind) {
    this.street = street;
    this.city = city;
    this.kind = kind;
  }

  @JsonProperty("street")
  @NotNull(message = "must not be null")
  public String getStreet() {
    return street;
  }

  @JsonProperty("city")
  @NotNull(message = "must not be null")
  public String getCity() {
    return city;
  }

  @JsonProperty("kind")
  @NotNull(message = "must not be null")
  @Pattern(regexp = "^(\\QRESIDENTIAL\\E|\\QCOMMERCIAL\\E)$", message = "must be one of RESIDENTIAL, COMMERCIAL")
  public String getKind() {
    return kind;
  }

  public Builder mutate() {
    return builder()
        .street(street)
        .city(city)
        .kind(kind);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Address other)) {
      return false;
    }
    return Objects.equals(street, other.street)
      && Objects.equals(city, other.city)
      && Objects.equals(kind, other.kind);
  }

  @Override
  public int hashCode() {
    return Objects.hash(street, city, kind);
  }

  @Override
  public String toString() {
    return "Address["
      + "street=" + street
      + ", city=" + city
      + ", kind=" + kind
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String street;
    private @Nullable String city;
    private @Nullable String kind;

    @Override
    public Builder street(@Nullable String street) {
      this.street = street;
      return this;
    }

    @Override
    public Builder city(@Nullable String city) {
      this.city = city;
      return this;
    }

    @Override
    public Builder kind(@Nullable String kind) {
      this.kind = kind;
      return this;
    }

    @Override
    public String toString() {
      return "Address.Builder["
        + "street=" + street
        + ", city=" + city
        + ", kind=" + kind
        + "]";
    }

    public Address build() {
      return new Address(
          Objects.requireNonNull(street, "street is required"),
          Objects.requireNonNull(city, "city is required"),
          Objects.requireNonNull(kind, "kind is required"));
    }
  }

  public sealed interface BuilderMutator permits Builder {

    BuilderMutator street(@Nullable String street);

    BuilderMutator city(@Nullable String city);

    BuilderMutator kind(@Nullable String kind);
  }
}
