package com.example.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.NotNull;
import java.util.Arrays;
import java.util.Base64;
import java.util.Objects;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@NullMarked
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonPropertyOrder({"id", "payload", "signature"})
public final class Blob {

  private final String id;

  private final byte[] payload;

  private final @Nullable byte[] signature;

  @JsonCreator
  Blob(
      @JsonProperty("id") String id,
      @JsonProperty("payload") byte[] payload,
      @JsonProperty("signature") @Nullable byte[] signature) {
    this.id = id;
    this.payload = payload;
    this.signature = signature;
  }

  @JsonProperty("id")
  @NotNull(message = "must not be null")
  public String getId() {
    return id;
  }

  @JsonProperty("payload")
  @NotNull(message = "must not be null")
  public byte[] getPayload() {
    return payload.clone();
  }

  @JsonProperty("signature")
  public @Nullable byte[] getSignature() {
    return signature != null ? signature.clone() : null;
  }

  public Builder mutate() {
    return builder()
        .id(id)
        .payload(payload)
        .signature(signature);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Blob other)) {
      return false;
    }
    return Objects.equals(id, other.id)
      && Arrays.equals(payload, other.payload)
      && Arrays.equals(signature, other.signature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, Arrays.hashCode(payload), Arrays.hashCode(signature));
  }

  @Override
  public String toString() {
    return "Blob["
      + "id=" + id
      + ", payload=" + Base64.getEncoder().encodeToString(payload)
      + ", signature=" + (signature != null ? Base64.getEncoder().encodeToString(signature) : "null")
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String id;
    private @Nullable byte[] payload;
    private @Nullable byte[] signature;

    @Override
    public Builder id(@Nullable String id) {
      this.id = id;
      return this;
    }

    @Override
    public Builder payload(@Nullable byte[] payload) {
      this.payload = payload != null ? payload.clone() : null;
      return this;
    }

    @Override
    public Builder signature(@Nullable byte[] signature) {
      this.signature = signature != null ? signature.clone() : null;
      return this;
    }

    @Override
    public String toString() {
      return "Blob.Builder["
        + "id=" + id
        + ", payload=" + (payload != null ? Base64.getEncoder().encodeToString(payload) : "null")
        + ", signature=" + (signature != null ? Base64.getEncoder().encodeToString(signature) : "null")
        + "]";
    }

    public Blob build() {
      return new Blob(
          Objects.requireNonNull(id, "id is required"),
          Objects.requireNonNull(payload, "payload is required"),
          signature);
    }
  }

  public sealed interface BuilderMutator permits Builder {

    BuilderMutator id(@Nullable String id);

    BuilderMutator payload(@Nullable byte[] payload);

    BuilderMutator signature(@Nullable byte[] signature);
  }
}
