package com.example.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
@NullMarked
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonPropertyOrder({"id", "billTo", "notes"})
public final class Invoice {

  @NotNull(message = "must not be null")
  private final String id;

  @NotNull(message = "must not be null")
  @Valid
  private final Contact billTo;

  @NotNull(message = "must not be null")
  private final List<@Valid Note> notes;

  @JsonCreator
  Invoice(
      @JsonProperty("id") String id,
      @JsonProperty("billTo") Contact billTo,
      @JsonProperty("notes") List<Note> notes) {
    this.id = id;
    this.billTo = billTo;
    this.notes = notes;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("billTo")
  public Contact getBillTo() {
    return billTo;
  }

  @JsonProperty("notes")
  public List<Note> getNotes() {
    return Collections.unmodifiableList(notes);
  }

  public Builder mutate() {
    return builder()
        .id(id)
        .billTo(billTo)
        .notes(notes);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Invoice other)) {
      return false;
    }
    return Objects.equals(id, other.id)
      && Objects.equals(billTo, other.billTo)
      && Objects.equals(notes, other.notes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, billTo, notes);
  }

  @Override
  public String toString() {
    return "Invoice["
      + "id=" + id
      + ", billTo=" + billTo
      + ", notes=" + notes
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  @Generated("io.github.malczuuu.modelmaker")
  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String id;
    private @Nullable Contact billTo;
    private @Nullable List<Note> notes;

    @Override
    public Builder id(@Nullable String id) {
      this.id = id;
      return this;
    }

    @Override
    public Builder billTo(@Nullable Contact billTo) {
      this.billTo = billTo;
      return this;
    }

    @Override
    public Builder notes(@Nullable List<Note> notes) {
      this.notes = notes;
      return this;
    }

    @Override
    public String toString() {
      return "Invoice.Builder["
        + "id=" + id
        + ", billTo=" + billTo
        + ", notes=" + notes
        + "]";
    }

    public Invoice build() {
      return new Invoice(
          Objects.requireNonNull(id, "id is required"),
          Objects.requireNonNull(billTo, "billTo is required"),
          new ArrayList<>(Objects.requireNonNull(notes, "notes is required")));
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  @JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPropertyOrder({"name", "email"})
  public static final class Contact {

    @NotNull(message = "must not be null")
    private final String name;

    @NotNull(message = "must not be null")
    private final String email;

    @JsonCreator
    Contact(
        @JsonProperty("name") String name,
        @JsonProperty("email") String email) {
      this.name = name;
      this.email = email;
    }

    @JsonProperty("name")
    public String getName() {
      return name;
    }

    @JsonProperty("email")
    public String getEmail() {
      return email;
    }

    public Builder mutate() {
      return builder()
          .name(name)
          .email(email);
    }

    @Override
    public boolean equals(@Nullable Object obj) {
      if (this == obj) {
        return true;
      }
      if (!(obj instanceof Contact other)) {
        return false;
      }
      return Objects.equals(name, other.name)
        && Objects.equals(email, other.email);
    }

    @Override
    public int hashCode() {
      return Objects.hash(name, email);
    }

    @Override
    public String toString() {
      return "Contact["
        + "name=" + name
        + ", email=" + email
        + "]";
    }

    public static Builder builder() {
      return new Builder();
    }

    @Generated("io.github.malczuuu.modelmaker")
    public static final class Builder implements BuilderMutator {

      private Builder() {}

      private @Nullable String name;
      private @Nullable String email;

      @Override
      public Builder name(@Nullable String name) {
        this.name = name;
        return this;
      }

      @Override
      public Builder email(@Nullable String email) {
        this.email = email;
        return this;
      }

      @Override
      public String toString() {
        return "Contact.Builder["
          + "name=" + name
          + ", email=" + email
          + "]";
      }

      public Contact build() {
        return new Contact(
            Objects.requireNonNull(name, "name is required"),
            Objects.requireNonNull(email, "email is required"));
      }
    }

    @Generated("io.github.malczuuu.modelmaker")
    public sealed interface BuilderMutator permits Builder {

      BuilderMutator name(@Nullable String name);

      BuilderMutator email(@Nullable String email);
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  @JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPropertyOrder({"author", "text"})
  public static final class Note {

    @NotNull(message = "must not be null")
    private final String author;

    @NotNull(message = "must not be null")
    private final String text;

    @JsonCreator
    Note(
        @JsonProperty("author") String author,
        @JsonProperty("text") String text) {
      this.author = author;
      this.text = text;
    }

    @JsonProperty("author")
    public String getAuthor() {
      return author;
    }

    @JsonProperty("text")
    public String getText() {
      return text;
    }

    public Builder mutate() {
      return builder()
          .author(author)
          .text(text);
    }

    @Override
    public boolean equals(@Nullable Object obj) {
      if (this == obj) {
        return true;
      }
      if (!(obj instanceof Note other)) {
        return false;
      }
      return Objects.equals(author, other.author)
        && Objects.equals(text, other.text);
    }

    @Override
    public int hashCode() {
      return Objects.hash(author, text);
    }

    @Override
    public String toString() {
      return "Note["
        + "author=" + author
        + ", text=" + text
        + "]";
    }

    public static Builder builder() {
      return new Builder();
    }

    @Generated("io.github.malczuuu.modelmaker")
    public static final class Builder implements BuilderMutator {

      private Builder() {}

      private @Nullable String author;
      private @Nullable String text;

      @Override
      public Builder author(@Nullable String author) {
        this.author = author;
        return this;
      }

      @Override
      public Builder text(@Nullable String text) {
        this.text = text;
        return this;
      }

      @Override
      public String toString() {
        return "Note.Builder["
          + "author=" + author
          + ", text=" + text
          + "]";
      }

      public Note build() {
        return new Note(
            Objects.requireNonNull(author, "author is required"),
            Objects.requireNonNull(text, "text is required"));
      }
    }

    @Generated("io.github.malczuuu.modelmaker")
    public sealed interface BuilderMutator permits Builder {

      BuilderMutator author(@Nullable String author);

      BuilderMutator text(@Nullable String text);
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  public sealed interface BuilderMutator permits Builder {

    BuilderMutator id(@Nullable String id);

    BuilderMutator billTo(@Nullable Contact billTo);

    BuilderMutator notes(@Nullable List<Note> notes);
  }
}
