package com.example.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import java.util.Objects;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
@NullMarked
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonPropertyOrder({"sku", "quantity", "unit"})
public final class LineItem {

  private final String sku;

  private final Long quantity;

  private final String unit;

  @JsonCreator
  LineItem(
      @JsonProperty("sku") String sku,
      @JsonProperty("quantity") Long quantity,
      @JsonProperty("unit") String unit) {
    this.sku = sku;
    this.quantity = quantity;
    this.unit = unit;
  }

  @JsonProperty("sku")
  @NotNull(message = "must not be null")
  public String getSku() {
    return sku;
  }

  @JsonProperty("quantity")
  @NotNull(message = "must not be null")
  public Long getQuantity() {
    return quantity;
  }

  @JsonProperty("unit")
  @NotNull(message = "must not be null")
  @Pattern(regexp = "^(\\QEACH\\E|\\QCASE\\E|\\QPALLET\\E)$", message = "must be one of EACH, CASE, PALLET")
  public String getUnit() {
    return unit;
  }

  public Builder mutate() {
    return builder()
        .sku(sku)
        .quantity(quantity)
        .unit(unit);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof LineItem other)) {
      return false;
    }
    return Objects.equals(sku, other.sku)
      && Objects.equals(quantity, other.quantity)
      && Objects.equals(unit, other.unit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sku, quantity, unit);
  }

  @Override
  public String toString() {
    return "LineItem["
      + "sku=" + sku
      + ", quantity=" + quantity
      + ", unit=" + unit
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  @Generated("io.github.malczuuu.modelmaker")
  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String sku;
    private @Nullable Long quantity;
    private @Nullable String unit;

    @Override
    public Builder sku(@Nullable String sku) {
      this.sku = sku;
      return this;
    }

    @Override
    public Builder quantity(@Nullable Long quantity) {
      this.quantity = quantity;
      return this;
    }

    @Override
    public Builder unit(@Nullable String unit) {
      this.unit = unit;
      return this;
    }

    @Override
    public String toString() {
      return "LineItem.Builder["
        + "sku=" + sku
        + ", quantity=" + quantity
        + ", unit=" + unit
        + "]";
    }

    public LineItem build() {
      return new LineItem(
          Objects.requireNonNull(sku, "sku is required"),
          Objects.requireNonNull(quantity, "quantity is required"),
          Objects.requireNonNull(unit, "unit is required"));
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  public sealed interface BuilderMutator permits Builder {

    BuilderMutator sku(@Nullable String sku);

    BuilderMutator quantity(@Nullable Long quantity);

    BuilderMutator unit(@Nullable String unit);
  }
}
