package com.example.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
@NullMarked
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonPropertyOrder({"id", "status", "shippingAddress", "items", "discountRate", "priority"})
public final class Order {

  @NotNull(message = "must not be null")
  private final String id;

  @NotNull(message = "must not be null")
  @Pattern(regexp = "^(\\QNEW\\E|\\QPAID\\E|\\QSHIPPED\\E)$", message = "must be one of NEW, PAID, SHIPPED")
  private final String status;

  @NotNull(message = "must not be null")
  @Valid
  private final Address shippingAddress;

  @NotNull(message = "must not be null")
  private final List<@Valid LineItem> items;

  private final @Nullable Float discountRate;

  @NotNull(message = "must not be null")
  @Pattern(regexp = "^(\\QLOW\\E|\\QNORMAL\\E|\\QHIGH\\E)$", message = "must be one of LOW, NORMAL, HIGH")
  private final String priority;

  @JsonCreator
  Order(
      @JsonProperty("id") String id,
      @JsonProperty("status") String status,
      @JsonProperty("shippingAddress") Address shippingAddress,
      @JsonProperty("items") List<@Valid LineItem> items,
      @JsonProperty("discountRate") @Nullable Float discountRate,
      @JsonProperty("priority") @Nullable String priority) {
    this.id = id;
    this.status = status;
    this.shippingAddress = shippingAddress;
    this.items = items;
    this.discountRate = discountRate;
    this.priority = priority != null ? priority : "NORMAL";
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("status")
  public String getStatus() {
    return status;
  }

  @JsonProperty("shippingAddress")
  public Address getShippingAddress() {
    return shippingAddress;
  }

  @JsonProperty("items")
  public List<@Valid LineItem> getItems() {
    return Collections.unmodifiableList(items);
  }

  @JsonProperty("discountRate")
  public @Nullable Float getDiscountRate() {
    return discountRate;
  }

  @JsonProperty("priority")
  public String getPriority() {
    return priority;
  }

  public Builder mutate() {
    return builder()
        .id(id)
        .status(status)
        .shippingAddress(shippingAddress)
        .items(items)
        .discountRate(discountRate)
        .priority(priority);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Order other)) {
      return false;
    }
    return Objects.equals(id, other.id)
      && Objects.equals(status, other.status)
      && Objects.equals(shippingAddress, other.shippingAddress)
      && Objects.equals(items, other.items)
      && Objects.equals(discountRate, other.discountRate)
      && Objects.equals(priority, other.priority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, shippingAddress, items, discountRate, priority);
  }

  @Override
  public String toString() {
    return "Order["
      + "id=" + id
      + ", status=" + status
      + ", shippingAddress=" + shippingAddress
      + ", items=" + items
      + ", discountRate=" + discountRate
      + ", priority=" + priority
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  @Generated("io.github.malczuuu.modelmaker")
  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String id;
    private @Nullable String status;
    private @Nullable Address shippingAddress;
    private @Nullable List<@Valid LineItem> items;
    private @Nullable Float discountRate;
    private @Nullable String priority;

    @Override
    public Builder id(@Nullable String id) {
      this.id = id;
      return this;
    }

    @Override
    public Builder status(@Nullable String status) {
      this.status = status;
      return this;
    }

    @Override
    public Builder shippingAddress(@Nullable Address shippingAddress) {
      this.shippingAddress = shippingAddress;
      return this;
    }

    @Override
    public Builder items(@Nullable List<@Valid LineItem> items) {
      this.items = items;
      return this;
    }

    @Override
    public Builder discountRate(@Nullable Float discountRate) {
      this.discountRate = discountRate;
      return this;
    }

    @Override
    public Builder priority(@Nullable String priority) {
      this.priority = priority;
      return this;
    }

    @Override
    public String toString() {
      return "Order.Builder["
        + "id=" + id
        + ", status=" + status
        + ", shippingAddress=" + shippingAddress
        + ", items=" + items
        + ", discountRate=" + discountRate
        + ", priority=" + priority
        + "]";
    }

    public Order build() {
      return new Order(
          Objects.requireNonNull(id, "id is required"),
          Objects.requireNonNull(status, "status is required"),
          Objects.requireNonNull(shippingAddress, "shippingAddress is required"),
          new ArrayList<>(Objects.requireNonNull(items, "items is required")),
          discountRate,
          priority);
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  public sealed interface BuilderMutator permits Builder {

    BuilderMutator id(@Nullable String id);

    BuilderMutator status(@Nullable String status);

    BuilderMutator shippingAddress(@Nullable Address shippingAddress);

    BuilderMutator items(@Nullable List<@Valid LineItem> items);

    BuilderMutator discountRate(@Nullable Float discountRate);

    BuilderMutator priority(@Nullable String priority);
  }
}
