/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.modelmaker;

/** Shared string constants used by the emitters. */
final class Constants {

  private Constants() {}

  /**
   * This generator's name, as it appears in the do-not-edit banner of every generated file.
   *
   * <p>Deliberately not emitted as a {@code javax.annotation.processing.Generated} annotation: that
   * would force every consumer with a {@code module-info.java} to {@code requires java.compiler},
   * and the banner already says the same thing.
   */
  static final String GENERATOR_NAME = "io.github.malczuuu.modelmaker";

  /**
   * Line comment stamped after the imports of every generated file, in both Java and Kotlin (both
   * use {@code //}). Not Javadoc - it is not attached to any declaration, just a do-not-edit
   * banner.
   */
  static final String GENERATED_FILE_NOTICE =
      "// Generated by ModelMaker (" + GENERATOR_NAME + "). Do not edit manually.";
}
