/*
 * Copyright 2026-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.malczuuu.modelmaker;

/** Shared string constants used by the emitters. */
final class Constants {

  private Constants() {}

  /**
   * The value of the {@code javax.annotation.processing.Generated} annotation stamped on every
   * generated type, so coverage / style tooling and readers can tell generated code apart.
   */
  static final String GENERATOR_NAME = "io.github.malczuuu.modelmaker";

  /**
   * Line comment stamped after the imports of every generated file, in both Java and Kotlin (both
   * use {@code //}). Not Javadoc - it is not attached to any declaration, just a do-not-edit
   * banner.
   */
  static final String GENERATED_FILE_NOTICE =
      "// Generated by ModelMaker (" + GENERATOR_NAME + "). Do not edit manually.";
}
