#!/bin/bash

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

cd example-avro/ ; ./gradlew "$@" ; cd ../
cd example-jackson/ ; ./gradlew "$@" ; cd ../
cd example-mutator/ ; ./gradlew "$@" ; cd ../
cd example-openapi/ ; ./gradlew "$@" ; cd ../
cd example-validation/ ; ./gradlew "$@" ; cd ../

cd example-maven/ ; ./mvnw package ; cd ../
