package com.example.dto;

import java.util.Objects;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
@NullMarked
public final class Point {

  private final int x;

  private final int y;

  private Point(
      int x,
      int y) {
    this.x = x;
    this.y = y;
  }

  public int getX() {
    return x;
  }

  public int getY() {
    return y;
  }

  public Point withX(int x) {
    return new Point(x, this.y);
  }

  public Point withY(int y) {
    return new Point(this.x, y);
  }

  public Builder mutate() {
    return builder()
        .x(x)
        .y(y);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Point other)) {
      return false;
    }
    return x == other.x
      && y == other.y;
  }

  @Override
  public int hashCode() {
    return Objects.hash(x, y);
  }

  @Override
  public String toString() {
    return "Point["
      + "x=" + x
      + ", y=" + y
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  @Generated("io.github.malczuuu.modelmaker")
  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable Integer x;
    private @Nullable Integer y;

    @Override
    public Builder x(@Nullable Integer x) {
      this.x = x;
      return this;
    }

    @Override
    public Builder y(@Nullable Integer y) {
      this.y = y;
      return this;
    }

    @Override
    public String toString() {
      return "Point.Builder["
        + "x=" + x
        + ", y=" + y
        + "]";
    }

    public Point build() {
      return new Point(
          Objects.requireNonNull(x, "x is required"),
          Objects.requireNonNull(y, "y is required"));
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  public sealed interface BuilderMutator permits Builder {

    BuilderMutator x(@Nullable Integer x);

    BuilderMutator y(@Nullable Integer y);
  }
}
