package com.example.dto;

import java.util.Arrays;
import java.util.Base64;
import java.util.Objects;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
@NullMarked
public final class Profile {

  private final String id;

  private final @Nullable String nickname;

  private final byte[] avatar;

  private Profile(
      String id,
      @Nullable String nickname,
      byte[] avatar) {
    this.id = id;
    this.nickname = nickname;
    this.avatar = avatar;
  }

  public String getId() {
    return id;
  }

  public @Nullable String getNickname() {
    return nickname;
  }

  public byte[] getAvatar() {
    return avatar.clone();
  }

  public Profile withId(String id) {
    return new Profile(Objects.requireNonNull(id), this.nickname, this.avatar);
  }

  public Profile withNickname(@Nullable String nickname) {
    return new Profile(this.id, nickname, this.avatar);
  }

  public Profile withAvatar(byte[] avatar) {
    return new Profile(this.id, this.nickname, Objects.requireNonNull(avatar).clone());
  }

  public Builder mutate() {
    return builder()
        .id(id)
        .nickname(nickname)
        .avatar(avatar);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Profile other)) {
      return false;
    }
    return Objects.equals(id, other.id)
      && Objects.equals(nickname, other.nickname)
      && Arrays.equals(avatar, other.avatar);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nickname, Arrays.hashCode(avatar));
  }

  @Override
  public String toString() {
    return "Profile["
      + "id=" + id
      + ", nickname=" + nickname
      + ", avatar=" + Base64.getEncoder().encodeToString(avatar)
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  @Generated("io.github.malczuuu.modelmaker")
  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String id;
    private @Nullable String nickname;
    private @Nullable byte[] avatar;

    @Override
    public Builder id(@Nullable String id) {
      this.id = id;
      return this;
    }

    @Override
    public Builder nickname(@Nullable String nickname) {
      this.nickname = nickname;
      return this;
    }

    @Override
    public Builder avatar(@Nullable byte[] avatar) {
      this.avatar = avatar != null ? avatar.clone() : null;
      return this;
    }

    @Override
    public String toString() {
      return "Profile.Builder["
        + "id=" + id
        + ", nickname=" + nickname
        + ", avatar=" + (avatar != null ? Base64.getEncoder().encodeToString(avatar) : "null")
        + "]";
    }

    public Profile build() {
      return new Profile(
          Objects.requireNonNull(id, "id is required"),
          nickname,
          Objects.requireNonNull(avatar, "avatar is required"));
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  public sealed interface BuilderMutator permits Builder {

    BuilderMutator id(@Nullable String id);

    BuilderMutator nickname(@Nullable String nickname);

    BuilderMutator avatar(@Nullable byte[] avatar);
  }
}
