package com.example.dto;

import java.util.Objects;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
@NullMarked
public final class Profile {

  private final String id;

  private final @Nullable String nickname;

  private Profile(
      String id,
      @Nullable String nickname) {
    this.id = id;
    this.nickname = nickname;
  }

  public String getId() {
    return id;
  }

  public @Nullable String getNickname() {
    return nickname;
  }

  public Profile withId(String id) {
    return new Profile(Objects.requireNonNull(id), this.nickname);
  }

  public Profile withNickname(@Nullable String nickname) {
    return new Profile(this.id, nickname);
  }

  public Builder mutate() {
    return builder()
        .id(id)
        .nickname(nickname);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Profile other)) {
      return false;
    }
    return Objects.equals(id, other.id)
      && Objects.equals(nickname, other.nickname);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nickname);
  }

  @Override
  public String toString() {
    return "Profile["
      + "id=" + id
      + ", nickname=" + nickname
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  @Generated("io.github.malczuuu.modelmaker")
  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String id;
    private @Nullable String nickname;

    @Override
    public Builder id(@Nullable String id) {
      this.id = id;
      return this;
    }

    @Override
    public Builder nickname(@Nullable String nickname) {
      this.nickname = nickname;
      return this;
    }

    @Override
    public String toString() {
      return "Profile.Builder["
        + "id=" + id
        + ", nickname=" + nickname
        + "]";
    }

    public Profile build() {
      return new Profile(
          Objects.requireNonNull(id, "id is required"),
          nickname);
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  public sealed interface BuilderMutator permits Builder {

    BuilderMutator id(@Nullable String id);

    BuilderMutator nickname(@Nullable String nickname);
  }
}
