package com.example.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
@NullMarked
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonPropertyOrder({"id", "shippingAddress"})
public final class Order {

  private final String id;

  private final Address shippingAddress;

  @JsonCreator
  Order(
      @JsonProperty("id") String id,
      @JsonProperty("shippingAddress") Address shippingAddress) {
    this.id = id;
    this.shippingAddress = shippingAddress;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("shippingAddress")
  public Address getShippingAddress() {
    return shippingAddress;
  }

  public Builder mutate() {
    return builder()
        .id(id)
        .shippingAddress(shippingAddress);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Order other)) {
      return false;
    }
    return Objects.equals(id, other.id)
      && Objects.equals(shippingAddress, other.shippingAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, shippingAddress);
  }

  @Override
  public String toString() {
    return "Order["
      + "id=" + id
      + ", shippingAddress=" + shippingAddress
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  @Generated("io.github.malczuuu.modelmaker")
  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String id;
    private @Nullable Address shippingAddress;

    @Override
    public Builder id(@Nullable String id) {
      this.id = id;
      return this;
    }

    @Override
    public Builder shippingAddress(@Nullable Address shippingAddress) {
      this.shippingAddress = shippingAddress;
      return this;
    }

    @Override
    public String toString() {
      return "Order.Builder["
        + "id=" + id
        + ", shippingAddress=" + shippingAddress
        + "]";
    }

    public Order build() {
      return new Order(
          Objects.requireNonNull(id, "id is required"),
          Objects.requireNonNull(shippingAddress, "shippingAddress is required"));
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  public sealed interface BuilderMutator permits Builder {

    BuilderMutator id(@Nullable String id);

    BuilderMutator shippingAddress(@Nullable Address shippingAddress);
  }
}
