package com.example.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
@NullMarked
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonPropertyOrder({"id", "label", "priority"})
public final class Tag {

  private final String id;

  private final @Nullable String label;

  private final Integer priority;

  @JsonCreator
  Tag(
      @JsonProperty("id") String id,
      @JsonProperty("label") @Nullable String label,
      @JsonProperty("priority") @Nullable Integer priority) {
    this.id = id;
    this.label = label;
    this.priority = priority != null ? priority : 0;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("label")
  public @Nullable String getLabel() {
    return label;
  }

  @JsonProperty("priority")
  public Integer getPriority() {
    return priority;
  }

  public Builder mutate() {
    return builder()
        .id(id)
        .label(label)
        .priority(priority);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Tag other)) {
      return false;
    }
    return Objects.equals(id, other.id)
      && Objects.equals(label, other.label)
      && Objects.equals(priority, other.priority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, label, priority);
  }

  @Override
  public String toString() {
    return "Tag["
      + "id=" + id
      + ", label=" + label
      + ", priority=" + priority
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  @Generated("io.github.malczuuu.modelmaker")
  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String id;
    private @Nullable String label;
    private @Nullable Integer priority;

    @Override
    public Builder id(@Nullable String id) {
      this.id = id;
      return this;
    }

    @Override
    public Builder label(@Nullable String label) {
      this.label = label;
      return this;
    }

    @Override
    public Builder priority(@Nullable Integer priority) {
      this.priority = priority;
      return this;
    }

    @Override
    public String toString() {
      return "Tag.Builder["
        + "id=" + id
        + ", label=" + label
        + ", priority=" + priority
        + "]";
    }

    public Tag build() {
      return new Tag(
          Objects.requireNonNull(id, "id is required"),
          label,
          priority);
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  public sealed interface BuilderMutator permits Builder {

    BuilderMutator id(@Nullable String id);

    BuilderMutator label(@Nullable String label);

    BuilderMutator priority(@Nullable Integer priority);
  }
}
