#!/bin/bash

###############################################################################
#
#   An utility script to checking which Java version compiled each submodule
#   of this project.
#
###############################################################################

echo "===================================================="
echo "Verifying Java version for classes within JAR files."
echo ""
echo "  modelmaker     must be 61 (Java 17)"
echo "  plugin-gradle  must be 61 (Java 17)"
echo ""
echo "Note that JAR files must exist (./gradlew build)."
echo ""

echo "===== modelmaker ===="
javap \
    -verbose \
    -classpath modelmaker/build/libs/modelmaker-*-SNAPSHOT.jar \
    io.github.malczuuu.modelmaker.ModelMaker \
    | grep "major version"

echo ""

echo "===== plugin-gradle ===="
javap \
    -verbose \
    -classpath plugin-gradle/build/libs/modelmaker-gradle-plugin-*-SNAPSHOT.jar \
    io.github.malczuuu.modelmaker.gradle.ModelMakerPlugin \
    | grep "major version"
