package com.example.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
@NullMarked
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonPropertyOrder({"sku", "quantity"})
public final class LineItem {

  private final String sku;

  private final Integer quantity;

  @JsonCreator
  LineItem(
      @JsonProperty("sku") String sku,
      @JsonProperty("quantity") Integer quantity) {
    this.sku = sku;
    this.quantity = quantity;
  }

  @JsonProperty("sku")
  public String getSku() {
    return sku;
  }

  @JsonProperty("quantity")
  public Integer getQuantity() {
    return quantity;
  }

  public Builder mutate() {
    return builder()
        .sku(sku)
        .quantity(quantity);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof LineItem other)) {
      return false;
    }
    return Objects.equals(sku, other.sku)
      && Objects.equals(quantity, other.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sku, quantity);
  }

  @Override
  public String toString() {
    return "LineItem["
      + "sku=" + sku
      + ", quantity=" + quantity
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  @Generated("io.github.malczuuu.modelmaker")
  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String sku;
    private @Nullable Integer quantity;

    @Override
    public Builder sku(@Nullable String sku) {
      this.sku = sku;
      return this;
    }

    @Override
    public Builder quantity(@Nullable Integer quantity) {
      this.quantity = quantity;
      return this;
    }

    @Override
    public String toString() {
      return "LineItem.Builder["
        + "sku=" + sku
        + ", quantity=" + quantity
        + "]";
    }

    public LineItem build() {
      return new LineItem(
          Objects.requireNonNull(sku, "sku is required"),
          Objects.requireNonNull(quantity, "quantity is required"));
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  public sealed interface BuilderMutator permits Builder {

    BuilderMutator sku(@Nullable String sku);

    BuilderMutator quantity(@Nullable Integer quantity);
  }
}
