package com.example.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
@NullMarked
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonPropertyOrder({"id", "items"})
public final class Manifest {

  private final String id;

  private final List<LineItem> items;

  @JsonCreator
  Manifest(
      @JsonProperty("id") String id,
      @JsonProperty("items") List<LineItem> items) {
    this.id = id;
    this.items = items;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("items")
  public List<LineItem> getItems() {
    return Collections.unmodifiableList(items);
  }

  public Builder mutate() {
    return builder()
        .id(id)
        .items(items);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Manifest other)) {
      return false;
    }
    return Objects.equals(id, other.id)
      && Objects.equals(items, other.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, items);
  }

  @Override
  public String toString() {
    return "Manifest["
      + "id=" + id
      + ", items=" + items
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  @Generated("io.github.malczuuu.modelmaker")
  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String id;
    private @Nullable List<LineItem> items;

    @Override
    public Builder id(@Nullable String id) {
      this.id = id;
      return this;
    }

    @Override
    public Builder items(@Nullable List<LineItem> items) {
      this.items = items;
      return this;
    }

    @Override
    public String toString() {
      return "Manifest.Builder["
        + "id=" + id
        + ", items=" + items
        + "]";
    }

    public Manifest build() {
      return new Manifest(
          Objects.requireNonNull(id, "id is required"),
          new ArrayList<>(Objects.requireNonNull(items, "items is required")));
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  public sealed interface BuilderMutator permits Builder {

    BuilderMutator id(@Nullable String id);

    BuilderMutator items(@Nullable List<LineItem> items);
  }
}
