package com.example.dto;

import java.util.Objects;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
@NullMarked
public final class Kit {

  private final String id;

  private final Widget widget;

  private Kit(
      String id,
      Widget widget) {
    this.id = id;
    this.widget = widget;
  }

  public String getId() {
    return id;
  }

  public Widget getWidget() {
    return widget;
  }

  public Builder mutate() {
    return builder()
        .id(id)
        .widget(widget);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Kit other)) {
      return false;
    }
    return Objects.equals(id, other.id)
      && Objects.equals(widget, other.widget);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, widget);
  }

  @Override
  public String toString() {
    return "Kit["
      + "id=" + id
      + ", widget=" + widget
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  @Generated("io.github.malczuuu.modelmaker")
  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String id;
    private @Nullable Widget widget;

    @Override
    public Builder id(@Nullable String id) {
      this.id = id;
      return this;
    }

    @Override
    public Builder widget(@Nullable Widget widget) {
      this.widget = widget;
      return this;
    }

    @Override
    public String toString() {
      return "Kit.Builder["
        + "id=" + id
        + ", widget=" + widget
        + "]";
    }

    public Kit build() {
      return new Kit(
          Objects.requireNonNull(id, "id is required"),
          Objects.requireNonNull(widget, "widget is required"));
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  public sealed interface BuilderMutator permits Builder {

    BuilderMutator id(@Nullable String id);

    BuilderMutator widget(@Nullable Widget widget);
  }
}
