package com.example.dto;

import java.util.Objects;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@NullMarked
public final class Widget {

  private final String id;

  private final String name;

  private final @Nullable String note;

  private Widget(
      String id,
      String name,
      @Nullable String note) {
    this.id = id;
    this.name = name;
    this.note = note;
  }

  public String getId() {
    return id;
  }

  public String getName() {
    return name;
  }

  public @Nullable String getNote() {
    return note;
  }

  public Builder mutate() {
    return builder()
        .id(id)
        .name(name)
        .note(note);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Widget other)) {
      return false;
    }
    return Objects.equals(id, other.id)
      && Objects.equals(name, other.name)
      && Objects.equals(note, other.note);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, note);
  }

  @Override
  public String toString() {
    return "Widget["
      + "id=" + id
      + ", name=" + name
      + ", note=" + note
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String id;
    private @Nullable String name;
    private @Nullable String note;

    @Override
    public Builder id(@Nullable String id) {
      this.id = id;
      return this;
    }

    @Override
    public Builder name(@Nullable String name) {
      this.name = name;
      return this;
    }

    @Override
    public Builder note(@Nullable String note) {
      this.note = note;
      return this;
    }

    @Override
    public String toString() {
      return "Widget.Builder["
        + "id=" + id
        + ", name=" + name
        + ", note=" + note
        + "]";
    }

    public Widget build() {
      return new Widget(
          Objects.requireNonNull(id, "id is required"),
          Objects.requireNonNull(name, "name is required"),
          note);
    }
  }

  public sealed interface BuilderMutator permits Builder {

    BuilderMutator id(@Nullable String id);

    BuilderMutator name(@Nullable String name);

    BuilderMutator note(@Nullable String note);
  }
}
