package com.example.dto;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.util.Objects;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@NullMarked
public final class Address {

  private final String street;

  private final String city;

  private Address(
      String street,
      String city) {
    this.street = street;
    this.city = city;
  }

  @NotNull(message = "must not be null")
  @Size(min = 1, message = "size must be at least 1")
  public String getStreet() {
    return street;
  }

  @NotNull(message = "must not be null")
  @Size(min = 1, message = "size must be at least 1")
  public String getCity() {
    return city;
  }

  public Builder mutate() {
    return builder()
        .street(street)
        .city(city);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Address other)) {
      return false;
    }
    return Objects.equals(street, other.street)
      && Objects.equals(city, other.city);
  }

  @Override
  public int hashCode() {
    return Objects.hash(street, city);
  }

  @Override
  public String toString() {
    return "Address["
      + "street=" + street
      + ", city=" + city
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String street;
    private @Nullable String city;

    @Override
    public Builder street(@Nullable String street) {
      this.street = street;
      return this;
    }

    @Override
    public Builder city(@Nullable String city) {
      this.city = city;
      return this;
    }

    @Override
    public String toString() {
      return "Address.Builder["
        + "street=" + street
        + ", city=" + city
        + "]";
    }

    public Address build() {
      return new Address(
          Objects.requireNonNull(street, "street is required"),
          Objects.requireNonNull(city, "city is required"));
    }
  }

  public sealed interface BuilderMutator permits Builder {

    BuilderMutator street(@Nullable String street);

    BuilderMutator city(@Nullable String city);
  }
}
