package com.example.dto;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import java.util.Objects;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@NullMarked
public final class LineItem {

  private final String sku;

  private final Integer quantity;

  private LineItem(
      String sku,
      Integer quantity) {
    this.sku = sku;
    this.quantity = quantity;
  }

  @NotNull(message = "must not be null")
  @Pattern(regexp = "^[A-Z0-9]+$", message = "must match \"^[A-Z0-9]+$\"")
  public String getSku() {
    return sku;
  }

  @NotNull(message = "must not be null")
  @Min(value = 1, message = "must be greater than or equal to 1")
  public Integer getQuantity() {
    return quantity;
  }

  public Builder mutate() {
    return builder()
        .sku(sku)
        .quantity(quantity);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof LineItem other)) {
      return false;
    }
    return Objects.equals(sku, other.sku)
      && Objects.equals(quantity, other.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sku, quantity);
  }

  @Override
  public String toString() {
    return "LineItem["
      + "sku=" + sku
      + ", quantity=" + quantity
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String sku;
    private @Nullable Integer quantity;

    @Override
    public Builder sku(@Nullable String sku) {
      this.sku = sku;
      return this;
    }

    @Override
    public Builder quantity(@Nullable Integer quantity) {
      this.quantity = quantity;
      return this;
    }

    @Override
    public String toString() {
      return "LineItem.Builder["
        + "sku=" + sku
        + ", quantity=" + quantity
        + "]";
    }

    public LineItem build() {
      return new LineItem(
          Objects.requireNonNull(sku, "sku is required"),
          Objects.requireNonNull(quantity, "quantity is required"));
    }
  }

  public sealed interface BuilderMutator permits Builder {

    BuilderMutator sku(@Nullable String sku);

    BuilderMutator quantity(@Nullable Integer quantity);
  }
}
