package com.example.dto;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@NullMarked
public final class Manifest {

  private final String id;

  private final List<LineItem> items;

  private final @Nullable List<String> tags;

  private Manifest(
      String id,
      List<LineItem> items,
      @Nullable List<String> tags) {
    this.id = id;
    this.items = items;
    this.tags = tags;
  }

  @NotNull(message = "must not be null")
  public String getId() {
    return id;
  }

  @NotNull(message = "must not be null")
  @Size(min = 1, max = 5, message = "size must be between 1 and 5")
  public List<@Valid LineItem> getItems() {
    return Collections.unmodifiableList(items);
  }

  @Size(max = 10, message = "size must be at most 10")
  public @Nullable List<@Pattern(regexp = "^[a-z-]+$", message = "must match \"^[a-z-]+$\"") @Size(min = 1, max = 40, message = "size must be between 1 and 40") String> getTags() {
    return tags != null ? Collections.unmodifiableList(tags) : null;
  }

  public Builder mutate() {
    return builder()
        .id(id)
        .items(items)
        .tags(tags);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Manifest other)) {
      return false;
    }
    return Objects.equals(id, other.id)
      && Objects.equals(items, other.items)
      && Objects.equals(tags, other.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, items, tags);
  }

  @Override
  public String toString() {
    return "Manifest["
      + "id=" + id
      + ", items=" + items
      + ", tags=" + tags
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String id;
    private @Nullable List<LineItem> items;
    private @Nullable List<String> tags;

    @Override
    public Builder id(@Nullable String id) {
      this.id = id;
      return this;
    }

    @Override
    public Builder items(@Nullable List<LineItem> items) {
      this.items = items;
      return this;
    }

    @Override
    public Builder tags(@Nullable List<String> tags) {
      this.tags = tags;
      return this;
    }

    @Override
    public String toString() {
      return "Manifest.Builder["
        + "id=" + id
        + ", items=" + items
        + ", tags=" + tags
        + "]";
    }

    public Manifest build() {
      return new Manifest(
          Objects.requireNonNull(id, "id is required"),
          new ArrayList<>(Objects.requireNonNull(items, "items is required")),
          tags != null ? new ArrayList<>(tags) : null);
    }
  }

  public sealed interface BuilderMutator permits Builder {

    BuilderMutator id(@Nullable String id);

    BuilderMutator items(@Nullable List<LineItem> items);

    BuilderMutator tags(@Nullable List<String> tags);
  }
}
