package com.example.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.util.Objects;
import javax.annotation.processing.Generated;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

// Generated by ModelMaker (io.github.malczuuu.modelmaker). Do not edit manually.

@Generated("io.github.malczuuu.modelmaker")
@NullMarked
public final class Person {

  private final String id;

  private final String email;

  private final @Nullable Integer age;

  private final @Nullable String bio;

  private final Boolean active;

  private Person(
      String id,
      String email,
      @Nullable Integer age,
      @Nullable String bio,
      @Nullable Boolean active) {
    this.id = id;
    this.email = email;
    this.age = age;
    this.bio = bio;
    this.active = active != null ? active : true;
  }

  @NotNull(message = "must not be null")
  @Pattern(regexp = "^P\\d+$", message = "must match \"^P\\d+$\"")
  public String getId() {
    return id;
  }

  @NotNull(message = "must not be null")
  @Email(message = "must be a well-formed email address")
  public String getEmail() {
    return email;
  }

  @Min(value = 0, message = "must be greater than or equal to 0")
  @Max(value = 120, message = "must be less than or equal to 120")
  public @Nullable Integer getAge() {
    return age;
  }

  @Size(max = 200, message = "size must be at most 200")
  public @Nullable String getBio() {
    return bio;
  }

  @NotNull(message = "must not be null")
  public Boolean getActive() {
    return active;
  }

  public Builder mutate() {
    return builder()
        .id(id)
        .email(email)
        .age(age)
        .bio(bio)
        .active(active);
  }

  @Override
  public boolean equals(@Nullable Object obj) {
    if (this == obj) {
      return true;
    }
    if (!(obj instanceof Person other)) {
      return false;
    }
    return Objects.equals(id, other.id)
      && Objects.equals(email, other.email)
      && Objects.equals(age, other.age)
      && Objects.equals(bio, other.bio)
      && Objects.equals(active, other.active);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, email, age, bio, active);
  }

  @Override
  public String toString() {
    return "Person["
      + "id=" + id
      + ", email=" + email
      + ", age=" + age
      + ", bio=" + bio
      + ", active=" + active
      + "]";
  }

  public static Builder builder() {
    return new Builder();
  }

  @Generated("io.github.malczuuu.modelmaker")
  public static final class Builder implements BuilderMutator {

    private Builder() {}

    private @Nullable String id;
    private @Nullable String email;
    private @Nullable Integer age;
    private @Nullable String bio;
    private @Nullable Boolean active;

    @Override
    public Builder id(@Nullable String id) {
      this.id = id;
      return this;
    }

    @Override
    public Builder email(@Nullable String email) {
      this.email = email;
      return this;
    }

    @Override
    public Builder age(@Nullable Integer age) {
      this.age = age;
      return this;
    }

    @Override
    public Builder bio(@Nullable String bio) {
      this.bio = bio;
      return this;
    }

    @Override
    public Builder active(@Nullable Boolean active) {
      this.active = active;
      return this;
    }

    @Override
    public String toString() {
      return "Person.Builder["
        + "id=" + id
        + ", email=" + email
        + ", age=" + age
        + ", bio=" + bio
        + ", active=" + active
        + "]";
    }

    public Person build() {
      return new Person(
          Objects.requireNonNull(id, "id is required"),
          Objects.requireNonNull(email, "email is required"),
          age,
          bio,
          active);
    }
  }

  @Generated("io.github.malczuuu.modelmaker")
  public sealed interface BuilderMutator permits Builder {

    BuilderMutator id(@Nullable String id);

    BuilderMutator email(@Nullable String email);

    BuilderMutator age(@Nullable Integer age);

    BuilderMutator bio(@Nullable String bio);

    BuilderMutator active(@Nullable Boolean active);
  }
}
